// import { IProducts } from './Iproducts';
export const products = [
    {
        productId: 1,
        image: "../assets/Images/Aamras.jpg",
        productName: "Aam Ras",
        prize:80 ,
        availability: true,
        qnt: 1,
        Tag: [ 'Drinks','md'],
        rating: 4.1,
        productDescription: "a sweet and creamy Indian dessert made from ripe mango pulp."
    },
    {
        productId: 2,
        image: "../assets/Images/Khandvi.jpg",
        productName: "Khandvi",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['breakfast','sider'],
        rating: 4.1,
        productDescription: "delicate, rolled Gujarati snack made from gram flour and yogurt, seasoned with mustard seeds and garnished with coconut and cilantro."
    },
    {
        productId: 20,
        image: "../assets/Images/Undhiyu.jpg",
        productName: "Surti Undhiyu Puri",
        prize: 250,
        availability: true,
        qnt: 1,
        Tag: [ 'meal'],
        rating: 4.5,
        productDescription: "A popular Gujarati dish consisting of a mixed vegetable curry made with various seasonal vegetables, spices, and herbs, served with crispy fried puris."
    },
    {
        productId: 84,
        image: "../assets/Images/84.jpg",
        productName: "Kichdi-Kadi-papad",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: "Soulful comfort on a plate: Kadhi Khichdi, where the warm embrace of khichdi meets the tangy richness of kadhi, creating a perfect harmony of flavors. "
    },
    {
        productId: 74,
        image: "../assets/Images/74.jpg",
        productName: "Thepla-sukibhaji",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.4,
        productDescription: "Savor the flavors of Gujarat with Thepla – a thin, spiced flatbread made with whole wheat flour, fenugreek leaves, and a blend of aromatic spices. Perfect for a delightful and nutritious meal!"
    },
    {
        productId: 3,
        image: "../assets/Images/methigota.jpg",
        productName: "Methi na gota",
        prize: 60,
        availability: true,
        qnt: 1,
        Tag: [ 'breakfast','sider'],
        rating: 4.1,
        productDescription: "crispy Gujarati snack made from chickpea flour batter mixed with fenugreek leaves and spices, deep-fried to perfection."
    },
    {
        productId: 6,
        image: "../assets/Images/6.jpg",
        productName: "Shrikhand",
        prize: 160,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.1,
        productDescription: "Satisfy your sweet cravings with the rich and creamy goodness of Shrikhand – a luscious Indian dessert made from strained yogurt, delicately flavored with saffron, cardamom, and a touch of sweetness. A divine indulgence that captures the essence of tradition! "
    },
    {
        productId: 8,
        image: "../assets/Images/8.jpg",
        productName: "Gajar Ka Halva",
        prize: 180,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Indulge in the sweet symphony of Gajar ka Halwa – a rich and flavorful carrot dessert cooked to perfection with ghee, milk, and aromatic spices. A festive treat that warms both the heart and the palate!"
    },
    {
        productId: 9,
        image: "../assets/Images/9.jpg",
        productName: "Kheer",
        prize:80,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Delight in the creamy sweetness of Kheer – a classic Indian rice pudding infused with fragrant cardamom and garnished with nuts. A comforting dessert that transcends generations! "
    },
    {
        productId: 10,
        image: "../assets/Images/gjamun.jpg",
        productName: "Gulab Jamun",
        prize: 310,
        availability: true,
        qnt: 10,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Indulgence in every sphere: Gulab Jamun, a symphony of sweetness that melts in your mouth, leaving behind moments of pure bliss. "
    },
    {
        productId: 4,
        image: "../assets/Images/4.jfif",
        productName: "Rasgulla",
        prize: 80,
        availability: true,
        qnt: 5,
        Tag: [ 'dessert'],
        rating: 4.1,
        productDescription: "Dive into the spongy sweetness of Rasgulla – a melt-in-your-mouth delight made from fresh cottage cheese balls soaked in fragrant sugar syrup. A heavenly treat that captures the essence of Indian desserts!"
    },
    {
        productId: 5,
        image: "../assets/Images/5.jpg",
        productName: "Rasmalai",
        prize: 90,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.1,
        productDescription: "Delight in the exquisite sweetness of Rasmalai – soft, spongy cottage cheese patties immersed in a rich, creamy milk bath, adorned with saffron and pistachios. A divine treat that elevates the dessert experience! "
    },
    {
        productId: 11,
        image: "../assets/Images/11.jpg",
        productName: "Venilla Ice Cream",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Pure indulgence in every scoop: Vanilla Ice Cream, a timeless delight that transforms any moment into a sweet symphony."
    },
    {
        productId: 12,
        image: "../assets/Images/12.jpg",
        productName: "American Nuts",
        prize: 70,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Crunchy cravings meet creamy dreams: American Nuts Ice Cream, a symphony of textures that takes your taste buds on a delightful journey. "
    },
    {
        productId: 13,
        image: "../assets/Images/13.jpg",
        productName: "Chocolate Ice Cream",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Dive into decadence: Chocolate Ice Cream, where rich cocoa dreams and creamy indulgence create a blissful escape in every bite."
    },
    {
        productId: 14,
        image: "../assets/Images/Fafda-jalebi.jpg",
        productName: "Jalebi fafada",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: [ 'breakfast'],
        rating: 4.2,
        productDescription: "a classic Gujarati breakfast combination featuring crispy gram flour fafda served with sweet and syrupy jalebi.."
    },
    {
        productId: 15,
        image: "../assets/Images/laddu.jpg",
        productName: "Motichur Laddu",
        prize: 300,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "traditional Indian sweet made from fine chickpea flour pearls, flavored with cardamom, and shaped into round balls."
    },
    {
        productId: 7,
        image: "../assets/Images/7.jpg",
        productName: "Modak",
        prize: 50,
        availability: true,
        qnt: 2,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "Savor the sweet charm of Modak – delicate rice flour dumplings filled with a luscious mixture of jaggery, coconut, and aromatic spices. An auspicious treat that captures the essence of festive celebrations! "
    },
    {
        productId: 16,
        image: "../assets/Images/RasPoori.jpg",
        productName: "Ras Puri",
        prize: 165,
        availability: true,
        qnt: 1,
        Tag: [ 'meal'],
        rating: 4.2,
        productDescription: "A traditional Indian dish featuring crispy puris served with a sweet and tangy spiced water (ras) for dipping."
    },
    {
        productId: 17,
        image: "../assets/Images/rabdi_jalebi.jpg",
        productName: "Jalebi Rabdi",
        prize: 150,
        availability: true,
        qnt: 1,
        Tag: [ 'dessert'],
        rating: 4.2,
        productDescription: "A decadent Indian dessert pairing crispy, syrup-soaked jalebis with rich, creamy rabdi (sweetened condensed milk)."
    },
    {
        productId: 18,
        image: "../assets/Images/MangoLassi.jpg",
        productName: "Mango Lassi",
        prize: 70,
        availability: true,
        qnt: 1,
        Tag: [ 'Drinks','md'],
        rating: 3.9,
        productDescription: "A refreshing Indian yogurt-based drink, either sweet or savory, often flavored with Mango."
    },
    {
        productId: 19,
        image: "../assets/Images/RoseLassi.jpg",
        productName: "Rose lassi",
        prize:60,
        availability: true,
        qnt: 1,
        Tag: [ 'Drinks','md'],
        rating: 3.9,
        productDescription: "A refreshing Indian yogurt-based drink, either sweet or savory, often flavored with Rose."
    },
    {
        productId: 21,
        image: "../assets/Images/khakhra.jpg",
        productName: "Khakhra",
        prize: 30,
        availability: true,
        qnt: 1,
        Tag: ['breakfast'],
        rating: 3.9,
        productDescription: "Thin, crispy Indian flatbread made from whole wheat flour, typically seasoned with spices."
    },
    {
        productId: 22,
        image: "../assets/Images/DalDhokli.jpg",
        productName: "Dal Dhokali",
        prize: 200,
        availability: true,
        qnt: 1,
        Tag: [ 'meal'],
        rating: 3.9,
        productDescription: ""
    },
    {
        productId: 26,
        image: "../assets/Images/26.jpg",
        productName: "French Fries",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['breakfast','sider'],
        rating: 4.3,
        productDescription: "side dish or snack typically made from deep-fried potatoes that have been cut into various shapes, especially thin strips. "
    },
    {
        productId: 27,
        image: "../assets/Images/27.jpg",
        productName: "Club Sandwitch",
        prize: 120,
        availability: true,
        qnt: 1,
        Tag: ['san'],
        rating: 4.3,
        productDescription: "Veg Club Sandwich is a traditional sandwich with veggies, mayonnaise filling , diced tomatoes layered in brown bread slices , grilled to perfection."
    },
    {
        productId: 28,
        image: "../assets/Images/28.jpg",
        productName: "Bread Butter",
        prize: 30,
        availability: true,
        qnt: 1,
        Tag: ['san'],
        rating: 4.3,
        productDescription: "Embracing the timeless duo of warm bread and creamy butter. "
    },
    {
        productId: 29,
        image: "../assets/Images/29.jpg",
        productName: "Bread Jam",
        prize: 30,
        availability: true,
        qnt: 1,
        Tag: ['san'],
        rating: 4.3,
        productDescription: "bread, butter, and jam. A symphony of flavors in every bite."
    },
    {
        productId: 30,
        image: "../assets/Images/30.jpg",
        productName: "Cheese Chutny sandwitch",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['san'],
        rating: 4.5,
        productDescription: "Savoring the delightful fusion of cheese and chutney in every layer of this scrumptious sandwich. A symphony of flavors between two slices of bliss! "
    },
    {
        productId:31,
        image: "../assets/Images/31.jpg",
        productName: "Cheese Chutny jam sandwitch",
        prize: 70,
        availability: true,
        qnt: 1,
        Tag: ['san'],
        rating: 4.5,
        productDescription: "Elevating the classic with a twist: Cheese, chutney, and jam unite in a sandwich symphony. Sweet, spicy, and cheesy perfection in every bite! "
    },
    {
        productId: 32,
        image: "../assets/Images/32.jpg",
        productName: "Mendu Vada",
        prize: 80,
        availability: true,
        qnt: 2,
        Tag: ['si'],
        rating: 4.5,
        productDescription: "Experience the crispy exterior and soft interior of Mendu Vada – a South Indian delight made from urad dal. Dunk it into chutney or sambar for a perfect symphony of textures and flavors!"
    },
    {
        productId: 33,
        image: "../assets/Images/33.jpg",
        productName: "Khaman",
        prize: 150,
        availability: true,
        qnt: 20,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Delight in the airy and tangy goodness of Khaman – a popular Gujarati snack made from fermented gram flour, adorned with mustard seeds and coriander. A steamed sensation that captures the essence of Indian flavors! "
    },
    {
        productId: 34,
        image: "../assets/Images/34.jpg",
        productName: "Dhokla",
        prize: 100,
        availability: true,
        qnt: 20,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Savor the light and fluffy texture of Dhokla – a steamed delicacy from Gujarat made with fermented rice and chickpea flour, tempered with mustard seeds and garnished with fresh coriander. A delightful treat that's both healthy and delicious!"
    },
    {
        productId: 35,
        image: "../assets/Images/35.jpg",
        productName: "Vada pav",
        prize: 25,
        availability: true,
        qnt: 1,
        Tag: ['breakfast'],
        rating: 4.5,
        productDescription: "Experience the street food delight of Vada Pav – a spiced potato patty encased in a gram flour batter, fried to perfection and served inside a soft pav with chutneys. A flavorful and iconic taste of Mumbai's bustling street food scene! "
    },
    {
        productId: 36,
        image: "../assets/Images/36.jpg",
        productName: "Batata vada",
        prize: 50,
        availability: true,
        qnt: 4,
        Tag: ['breakfast','sider'],
        rating: 4.2,
        productDescription: "Experience the crispy exterior and flavorful surprise within with Batata Vada – spiced mashed potato balls encased in a gram flour batter, fried to perfection. A delightful Indian snack that packs a punch of taste in every bite!"
    },
    {
        productId: 37,
        image: "../assets/Images/37.jpg",
        productName: "Bhel Puri",
        prize: 50,
        availability: true,
        qnt: 6,
        Tag: ['breakfast'],
        rating: 4.2,
        productDescription: "Crunchy, tangy, and utterly delicious – Bhel Puri is a flavorful street snack made with puffed rice, veggies, chutneys, and a burst of spices. A symphony of textures and tastes that brings the streets of India to your palate! "
    },
    {
        productId: 38,
        image: "../assets/Images/38.jpg",
        productName: "Dahi Puri",
        prize: 60,
        availability: true,
        qnt: 6,
        Tag: ['breakfast'],
        rating: 4.2,
        productDescription: "Delight in the burst of flavors with Dahi Puri – crisp puris filled with a tantalizing mix of spiced potatoes, sweet and tangy chutneys, and topped with cool yogurt. A bite-sized explosion of taste and texture! "
    },
    {
        productId: 39,
        image: "../assets/Images/39.jpg",
        productName: "Rajma",
        prize: 80,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: "Indulge in the heartiness of Rajma – a North Indian classic featuring red kidney beans cooked in a rich and flavorful tomato-based curry. A wholesome dish that comforts the soul with each spoonful!"
    },
    {
        productId: 40,
        image: "../assets/Images/40.jpg",
        productName: "Dabeli",
        prize: 25,
        availability: true,
        qnt: 1,
        Tag: ['breakfast'],
        rating: 4.2,
        productDescription: "Experience the delightful medley of flavors in every bite of Dabeli – a spiced potato mixture nestled inside a soft pav, generously garnished with chutneys, pomegranate seeds, and crunchy peanuts. A street food sensation that's truly irresistible! "
    },
    {
        productId: 87,
        image: "../assets/Images/87.jpg",
        productName: "Olo-rotla",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: ""
    },
    {
        productId: 41,
        image: "../assets/Images/41.jpg",
        productName: "Palak Paneer",
        prize: 130,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: "Experience the green goodness of Palak Paneer – succulent cubes of paneer enveloped in a rich and creamy spinach curry. A vibrant, wholesome dish that's a celebration of flavors and health! "
    },
    {
        productId: 42,
        image: "../assets/Images/42.jpg",
        productName: "Aloo Gobi",
        prize: 80,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.5,
        productDescription: "Enjoy the simple yet flavorful delight of Aloo Gobi – a classic Indian dish featuring potatoes and cauliflower cooked with aromatic spices. A comforting medley of textures and tastes that warms the heart!"
    },
    {
        productId: 43,
        image: "../assets/Images/43.jpg",
        productName: "Aloo Tikki",
        prize: 80,
        availability: true,
        qnt: 1,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Savor the crispiness and flavor burst of Aloo Tikki – golden potato patties, spiced to perfection and fried until golden brown. A street food favorite that brings joy with every crunchy bite! "
    },
    {
        productId: 44,
        image: "../assets/Images/44.jpg",
        productName: "Dahi Vada",
        prize: 60,
        availability: true,
        qnt: 4,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Delight in the cool and tangy bliss of Dahi Vada – soft lentil dumplings soaked in spiced yogurt and adorned with a medley of chutneys. A refreshing burst of flavors in every bite! "
    },
    {
        productId: 45,
        image: "../assets/Images/45.jpg",
        productName: "Masala Papad",
        prize: 30,
        availability: true,
        qnt: 1,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Elevate your appetizer game with Masala Papad – a crispy, thin papad topped with a zesty mix of tomatoes, onions, and spices. A tantalizing start to any meal! "
    },
    {
        productId: 46,
        image: "../assets/Images/46.jpg",
        productName: "samosa",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['breakfast','sider'],
        rating: 4.5,
        productDescription: "Golden triangles of delight: Samosas, the perfect blend of crispy crust and spiced filling, delivering joy in every bite."
    },
    {
        productId: 47,
        image: "../assets/Images/47.jpg",
        productName: "Hakka Noodles",
        prize: 200,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.5,
        productDescription: "Stir-fried perfection in every noodle! Dive into the wok-tossed symphony of flavors with these Hakka Noodles – a delightful dance of textures and tastes. "
    },
    {
        productId: 48,
        image: "../assets/Images/48.jpg",
        productName: "Manchurian",
        prize: 130,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.5,
        productDescription: "Craving a burst of flavors? Dive into the delectable world of Veg Manchurian – a tantalizing blend of vegetables, spices, and savory sauces. A true delight for your taste buds! "
    },
    {
        productId: 49,
        image: "../assets/Images/49.jpg",
        productName: "Gobi Manchurian",
        prize: 120,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.5,
        productDescription: "Embrace the crunchy and flavorful magic of Gobi Manchurian! Crispy cauliflower florets tossed in a delectable blend of spices and sauces – a perfect fusion of textures and taste. "
    },
    {
        productId: 50,
        image: "../assets/Images/50.jpg",
        productName: "schezwan noodles",
        prize: 200,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.6,
        productDescription: "Embark on a flavor-packed journey with Schezwan Noodles – a fiery fusion of wok-tossed noodles, vibrant vegetables, and the bold kick of Schezwan sauce. Spice up your palate! "
    },
    {
        productId: 51,
        image: "../assets/Images/51.jpg",
        productName: "chinese Bhel",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.6,
        productDescription: "Elevate your snack game with Chinese Bhel – a delightful fusion of crispy noodles, colorful veggies, and zesty sauces. A tantalizing twist on street food that's sure to tickle your taste buds! "
    },
    {
        productId: 52,
        image: "../assets/Images/52.jpg",
        productName: "Manchurian Rice",
        prize: 120,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.6,
        productDescription: "Dive into the deliciousness of Manchurian Rice – a perfect blend of aromatic fried rice and flavorful Manchurian balls. A symphony of textures and tastes in every mouthful! "
    },
    {
        productId: 53,
        image: "../assets/Images/53.jpg",
        productName: "Sweet Corn Soup",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['Drinks'],
        rating: 4.6,
        productDescription: "Sip into comfort with a bowl of Sweet Corn Soup. A warm embrace of delicate sweetness and savory goodness in every spoonful."
    },
    {
        productId: 54,
        image: "../assets/Images/54.jpg",
        productName: "Lassi",
        prize: 40,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.6,
        productDescription: "Quench your thirst and indulge in the creamy delight of Lassi. This traditional yogurt-based drink is a refreshing symphony of sweet and tangy goodness. "
    },
    {
        productId: 55,
        image: "../assets/Images/55.jpg",
        productName: "Masala Tea",
        prize: 10,
        availability: true,
        qnt: 1,
        Tag: ['Drinks'],
        rating: 4.5,
        productDescription: "Sip into comfort with a cup of Masala Tea – a fragrant blend of black tea, aromatic spices, and a touch of warmth. A flavorful journey to soothe the soul."
    },
    {
        productId: 56,
        image: "../assets/Images/56.jpg",
        productName: "Ginger Tea",
        prize: 15,
        availability: true,
        qnt: 1,
        Tag: ['Drinks'],
        rating: 4.5,
        productDescription: "Embrace the soothing warmth of Ginger Tea – a comforting infusion of black tea and freshly grated ginger. A delightful blend that invigorates your senses and provides a cozy escape with every sip."
    },
    {
        productId: 57,
        image: "../assets/Images/57.jpg",
        productName: "Coffee",
        prize: 90,
        availability: true,
        qnt: 1,
        Tag: ['Drinks'],
        rating: 4.5,
        productDescription: "Sip, savor, repeat: Coffee, the aromatic companion to moments of warmth and contemplation. "
    },
    {
        productId: 58,
        image: "../assets/Images/58.jpg",
        productName: "Thums Up",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.5,
        productDescription: "Bold, fizzy, and unapologetically original: Thums Up, the taste that packs a punch and sparks a symphony of refreshment."
    },
    {
        productId:59,
        image: "../assets/Images/59.jpg",
        productName: "Coca Cola",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.5,
        productDescription: "Pop, Fizz, Refresh: Coca-Cola, the timeless effervescence that turns moments into memories."
    },
    {
        productId: 60,
        image: "../assets/Images/60.jpg",
        productName: "7 Up",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.5,
        productDescription: "Crisp and Clear, Light and Bright: 7UP, the sparkling companion that elevates every sip with a burst of citrusy joy. "
    },
    {
        productId: 61,
        image: "../assets/Images/61.jpg",
        productName: "Pepsi",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.5,
        productDescription: "Bold, bubbly, and utterly refreshing: Pepsi, the ultimate companion for those who live for the thrill of the sip."
    },
    {
        productId: 62,
        image: "../assets/Images/62.jpg",
        productName: "Pulpy Orange",
        prize: 25,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.6,
        productDescription: "Sun-kissed delight in every sip: Pulpy Orange, where the refreshing burst of citrus meets the pure joy of pulpy goodness. "
    },
    {
        productId: 63,
        image: "../assets/Images/63.jpg",
        productName: "Chilli Paneer",
        prize: 250,
        availability: true,
        qnt: 1,
        Tag: ['chinese'],
        rating: 4.6,
        productDescription: "Spice up your day with the fiery goodness of Chilli Paneer! Succulent paneer cubes tossed in a zesty blend of spices and vibrant peppers – a flavor explosion that's impossible to resist."
    },
    {
        productId: 64,
        image: "../assets/Images/64.jpg",
        productName: "Fried Rice",
        prize: 150,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: "Dive into a bowl of Veg Fried Rice – a symphony of colorful veggies and perfectly seasoned rice, wok-tossed to perfection. A delightful journey of flavors in every forkful! "
    },
    {
        productId: 65,
        image: "../assets/Images/65.jpg",
        productName: "Chole Bhature ",
        prize: 70,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: "Indulge in the heavenly duo of Chole Bhature – pillowy soft bhaturas paired with spicy, tangy chickpeas. A match made in culinary bliss! "
    },
    {
        productId: 66,
        image: "../assets/Images/66.jpg",
        productName: "Bhature",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['roti'],
        rating: 4.6,
        productDescription: "Golden and fluffy, these Bhaturas are a feast for the senses. Crispy on the outside, soft on the inside – the perfect accompaniment to a world of flavors! "
    },
    {
        productId: 67,
        image: "../assets/Images/67.jpg",
        productName: "Makke di Roti",
        prize: 40,
        availability: true,
        qnt: 1,
        Tag: ['roti'],
        rating: 4.6,
        productDescription: "Savor the rustic goodness of Makke di Roti – a traditional cornmeal flatbread that's hearty, flavorful, and the perfect companion to a winter meal. Simple, yet soulful! "
    },
    {
        productId: 68,
        image: "../assets/Images/68.jpg",
        productName: "Aloo paratha",
        prize: 60,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: "Experience the warm embrace of homemade comfort with Aloo Paratha – golden, flaky bread stuffed with spiced potatoes. A culinary hug that brings joy to every bite! "
    },
    {
        productId: 69,
        image: "../assets/Images/69.jpg",
        productName: "Uttapam",
        prize: 60,
        availability: true,
        qnt: 1,
        Tag: ['si'],
        rating: 4.6,
        productDescription: "Savor the South Indian flavors with Uttapam – a savory pancake bursting with the goodness of fermented batter, topped with a colorful medley of veggies. A taste of tradition on your plate! "
    },
    {
        productId: 70,
        image: "../assets/Images/70.webp",
        productName: "idli sambhar",
        prize: 100,
        availability: true,
        qnt: 2,
        Tag: ['breakfast','si'],
        rating: 4.6,
        productDescription: "Embark on a culinary journey with the timeless combo of Idli and Sambar. Soft, steamed rice cakes served with a flavorful lentil soup – a South Indian symphony on your plate! "
    },
    {
        productId: 71,
        image: "../assets/Images/71.jpg",
        productName: "Biryani",
        prize: 100,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.6,
        productDescription: "Indulge in the aromatic delight of Veg Biryani – fragrant basmati rice, slow-cooked with a medley of vegetables, and infused with the rich blend of spices. A royal treat for the senses! "
    },
    {
        productId: 73,
        image: "../assets/Images/73.jpg",
        productName: "Naan",
        prize: 60,
        availability: true,
        qnt: 1,
        Tag: ['roti'],
        rating: 4.6,
        productDescription: "Soft, pillowy, and oven-baked to perfection – Naan, the quintessential Indian bread that complements every meal. A canvas for rich curries or a simple delight with a dollop of butter."
    },
    {
        productId: 75,
        image: "../assets/Images/75.jpg",
        productName: "Misal pav",
        prize: 80,
        availability: true,
        qnt: 2,
        Tag: ['meal'],
        rating: 4.4,
        productDescription: "Indulge in the bold and flavorful world of Misal Pav – a spicy, sprout-based curry garnished with crunchy farsan, chopped onions, and a squeeze of lime. Paired with pav, it's a taste explosion that captures the essence of Maharashtrian cuisine! "
    },
    {
        productId: 76,
        image: "../assets/Images/76.jpg",
        productName: "Pav Bhaji",
        prize: 100,
        availability: true,
        qnt: 2,
        Tag: ['meal'],
        rating: 4.4,
        productDescription: "Dive into the hearty goodness of Pav Bhaji – a medley of spiced mashed vegetables served with buttery pav. A flavorsome street food delight that brings the vibrant essence of Mumbai to your plate! "
    },
    {
        productId: 77,
        image: "../assets/Images/77.webp",
        productName: "Mysore Dosa",
        prize: 150,
        availability: true,
        qnt: 1,
        Tag: ['meal','si'],
        rating: 4.4,
        productDescription: "Embark on a culinary journey with the bold and spicy flavors of Mysore Dosa – a crispy delight smeared with a fiery chutney, awakening your taste buds with every bite! "
    },
    {
        productId: 78,
        image: "../assets/Images/78.jpg",
        productName: "Dal Tadaka",
        prize: 90,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.4,
        productDescription: "Dive into the soulful comfort of Dal Tadka – a fragrant lentil curry tempered with aromatic spices. Each spoonful is a warm embrace of flavors, making it a cherished part of every Indian meal."
    },
    {
        productId: 79,
        image: "../assets/Images/79.jpg",
        productName: "Dal Batti",
        prize: 90,
        availability: true,
        qnt: 1,
        Tag: ['meal'],
        rating: 4.4,
        productDescription: "Indulge in the rustic charm of Dal Batti – a traditional Rajasthani dish featuring lentils (dal) served with baked wheat balls (batti). A wholesome and hearty culinary experience that embodies the essence of Indian comfort food!"
    },
    {
        productId: 80,
        image: "../assets/Images/80.jpg",
        productName: "Masala Dosa",
        prize: 160,
        availability: true,
        qnt: 1,
        Tag: ['meal','si'],
        rating: 4.4,
        productDescription: "Experience the crispy allure and spicy flavors of Masala Dosa – a South Indian favorite. Thin, golden crepes filled with a delightful potato masala, served with coconut chutney and tangy sambar. A culinary symphony on your plate! "
    },
    {
        productId: 81,
        image: "../assets/Images/81.jpg",
        productName: "Rumali Roti",
        prize: 15,
        availability: true,
        qnt: 1,
        Tag: ['roti'],
        rating: 4.4,
        productDescription: "Simple joys, timeless traditions: A plateful of warmth and comfort with perfectly cooked Roti."
    },
    // {
    //     productId: 82,
    //     image: "../assets/Images/82.jpg",
    //     productName: "Coconut Chutney",
    //     prize: 20,
    //     availability: true,
    //     qnt: 1,
    //     Tag: ['meal','si'],
    //     rating: 4.6,
    //     productDescription: "Embrace the tropical twist: Coconut Chutney, a spoonful of freshness and flavor in every bite."
    // },
    {
        productId: 83,
        image: "../assets/Images/83.jpg",
        productName: "Paper Dosa",
        prize: 40,
        availability: true,
        qnt: 1,
        Tag: ['meal','si'],
        rating: 4.6,
        productDescription: "Crispy, thin, and simply irresistible: Paper Dosa, where every bite unfolds a symphony of flavors. "
    },
    {
        productId: 85,
        image: "../assets/Images/85.jpg",
        productName: "Manchaw Soup",
        prize: 120,
        availability: true,
        qnt: 1,
        Tag: ['Drinks'],
        rating: 4.6,
        productDescription: ""
    },
    {
        productId: 86,
        image: "../assets/Images/86.jpg",
        productName: "Chaas",
        prize: 20,
        availability: true,
        qnt: 1,
        Tag: ['Drinks','md'],
        rating: 4.6,
        productDescription: ""
    },
    {
        productId: 87,
        image: "../assets/Images/sukibhaji.jpg",
        productName: "Sukibhaji",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 88,
        image: "../assets/Images/Undhiyu_shak.jpg",
        productName: "Undhiyu",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 89,
        image: "../assets/Images/SevTameta.jpg",
        productName: "Sev-Tameta",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 90,
        image: "../assets/Images/AlooMatar.jpg",
        productName: "Bateta Vatana",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 91,
        image: "../assets/Images/BhindiMasala.jpg",
        productName: "Bhindi masala",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 92,
        image: "../assets/Images/ShahiPaneer.jpg",
        productName: "Shahi Paneer",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 93,
        image: "../assets/Images/PaneerBhurjijpg.jpg",
        productName: "Paneer Bhurji",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
    {
        productId: 94,
        image: "../assets/Images/MagnuShak.jpg",
        productName: "Mag Nu shak",
        prize: 50,
        availability: true,
        qnt: 1,
        Tag: ['shak'],
        rating: 4.2,
        productDescription: " "
    },
]
